### ISSUE TITLE
Data property on Sequence is a List<object>

### ISSUE THREAD

**Issue by ncipollina** [stoiveyp/Alexa.NET.APL#100]
Currently, the `Sequence` component has the `Data` property defined as `APLValue<List<object>>`. This will work great when I want to provide the data as a list of objects. But for the scenario where I want to reference a datasource because I'm using a transformer, this won't work because I need to be able to provide a string. Something like this:

```json
  {
      "type": "Sequence",
      "id": "leaderboardSequence",
      "width": "100%",
      "height": "80%",
      "data": "${payload.leaderboardData.properties.listItems}",
      "numbered": true,
      "items": [
```

Ideally it would be nice to be able to support both a list of objects _and_ a string so I can define this either way.

**Comment by stoiveyp** [comment]
Morning @ncipollina - All APLValue objects should be able to be represented as strings using the `.To(string)` method

I'm at work so I can't check the exact code right now, but if you take a look it should be something like `APLValue<List<object>>.To("${payload.leaderboardData.properties.listItems}")`

Let me know if that helps?

**Comment by ncipollina** [comment]
@stoiveyp thanks for the reply. I tried that and it ended up outputting this:

```json
   {
      "type": "Sequence",
      "id": "leaderboardSequence",
      "width": "100%",
      "height": "80%",
      "data": ["${payload.leaderboardData.properties.listItems}"],
      "numbered": true,
      "items": [
```

That theoretically should have worked, but it just generated an error.

**Comment by stoiveyp** [comment]
hmm it shouldn't have put it in the array, it should have referenced the string directly.
Are you able to paste just the line you use to set that Data property please and I'll take a look tonight to see what's happening

**Comment by stoiveyp** [comment]
That's great, thank you. 

As I can't get to it for hours yet (it's 1pm here and I won't be free until 9/10pm earliest) could you try the following line of code as an alternative and see if this changes the output at all?

`Data = APLValue<List<object>>.To("${payload.leaderboardData.properties.listItems}");`

Just want to see if that produces something more useable - if not then I'll debug when I'm available tonight 👍

**Comment by ncipollina** [comment]
I'll give it a try. Thanks!
