### ISSUE TITLE
ExecuteCommandsDirective Serialization

### ISSUE THREAD

**Issue by bauchschuss** [stoiveyp/Alexa.NET.APL#51]
Hi,
i had problems using ExecuteCommandsDirective with SpeakItem after updating to version 4.0.10 of the APL library. It is also possible that my problem has to do something with a change done by amazon.

I always got an response error when i had just one command added to the ExecuteCommandsDirective. I think the problem is that the Commands enumeration is not serialized as array when there is just one command in it. My Workaround is to add a second SpeakItem command with a not existing componentid property.

Workaround:
```
{
                "type": "Alexa.Presentation.APL.ExecuteCommands",
                "token": "WasteTipsDirective",
                "commands": [
                    {
                        "type": "SpeakItem",
                        "componentId": "fake"
                    },
                    {
                        "type": "SpeakItem",
                        "align": "center",
                        "componentId": "talker",
                        "highlightMode": "line"
                    }
                ]
            }
```

NOT WORKING:
```
{
                "type": "Alexa.Presentation.APL.ExecuteCommands",
                "token": "WasteTipsDirective",
                "commands": {
                    "type": "SpeakItem",
                        "align": "center",
                        "componentId": "talker",
                        "highlightMode": "line"
                }
            }
```

**Comment by stoiveyp** [comment]
Hi @bauchschuss - I've not looked at the directive for a while and the docs definitely specify an array now, so I've tweaked it to always output one - this is in v4.0.11 that's just been published

https://www.nuget.org/packages/Alexa.NET.APL/4.0.11
