### ISSUE TITLE
APLSupported Can Fail on NULL Object (Context)

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [stoiveyp/Alexa.NET.APL#52]
Migrating to APLSkillRequest means simplifying code with .APLSupported() rather than 
  request.Context?.System.Device.SupportedInterfaces.ContainsKey(InterfaceName)

However, in our tests Context can be null which is not handled by APLInterface.cs code because there is no ? null check

Assuming there are valid cases where .Context may be null (and System? and Device?) consider revising the code.  See also checks in APLInterfaceDetails()

**Comment by stoiveyp** [comment]
Hi @Crispin-at-Linknode, can you please confirm you have received a null context, or it's just null in your tests?

The reason I ask is that it's part of the request schema - so you should always receive a context, even in the developer console, which is why there's no null checks currently.

Cheers.

**Comment by Crispin-at-Linknode** [comment]
We have tests that create a new LaunchRequest() and then pass it to the code for the launch request handler -- hence my query as to if there are cases where Context may be null.  You have way more experience with the model than us so will look to ensure our tests put a context in of some form... new Alexa.NET.APL.APLContext() ?

**Comment by stoiveyp** [comment]
All devices should send a context. The default structure of a request can be quite involved, so it's often easier to capture one from either the developer console or an actual skill input - replace anything "real" with fake values (user id, api token etc) - then deserialize that and just alter the request type to match what you need 👍
