### ISSUE TITLE
Events should be an array

### ISSUE THREAD

**Issue by georgeduckett** [stoiveyp/Alexa.NET.APL#54]
Events (`onPress` in my case) appear to expect an array of actions now, rather than a single object. The documentation doesn't appear to reflect this change in all places, however the [APL designer](https://developer.amazon.com/alexa/console/ask/displays) does give warnings when you input something other than an array. The [onPress documentation of TouchWrapper](https://developer.amazon.com/docs/alexa-presentation-language/apl-touchwrapper.html#onpress) does refer to command(s) to execute though. The fix in my case seems to be making it an array of a single object, rather than the single object its self.

**Comment by stoiveyp** [comment]
Despite the warnings of the designer, the documentation isn't wrong - events can, almost everywhere, be a singular object or an array of objects. Which for a strongly typed languages I'm sure you can appreciate causes me no end of headaches.

There are parts of the library which if you examine the source code will show I'm using "single or list" converters to try and handle this problem. But they might allow me to look into more user defined options for serialization moving forward, I'll have a think about that.

Anyway - in your case the TouchWrapper has been on its own for a long time in that the OnPress property _had_ to be a SendEvent command. It looks like this finally got sorted and needs to be able to handle the usual "single or list" style options I give all the other commands.

I'm on holiday with the family at the moment so there may be a delay in getting a fix in - but I'll try and get this done as soon as I can. Thanks for raising it.

**Comment by georgeduckett** [comment]
Thanks for the in-depth explanation. It's not causing issues at the moment, I was just running through the designer warnings when troubleshooting the parameters issue #53.

I appreciate it's the holiday season at the moment (in some places, anyway); no rush from my side.

**Comment by stoiveyp** [comment]
Hi @georgeduckett - v4.1 https://www.nuget.org/packages/Alexa.NET.APL/4.1.0 now has the TouchWrapper control changed so that OnPress can handle any and all commands.

Until the designer starts sending this as a failure, or the team finally force arrays, I have to honour the "one or many" structure allowed by APL to ensure it doesn't break layouts that have been working up until now - within the code they will be lists of commands so I hope this helps.
