### ISSUE TITLE
Properties that are currently APLAbsoluteDimensionValue prevent using expressions

### ISSUE THREAD

**Issue by georgeduckett** [stoiveyp/Alexa.NET.APL#56]
I've just updated to 4.1.0, and gone from

    Top = "{Top}"

to

    Top = APLValue.To<APLAbsoluteDimensionValue>("${Top}")

This doesn't work however as the implicit conversion takes the `Value` property, which is null meaning nothing is output in JSON.

Since APL seems to allow `Top` (and probably others) to use a property I guess the type should be something like `APLValue<APLAbsoluteDimensionValue>`.

**Comment by stoiveyp** [comment]
Great catch @georgeduckett!

The number of valid dimension combinations and ensuring the type validity for Absolute dimensions took some time to get my tests passing again - but this is now sorted in [v4.1.2](https://www.nuget.org/packages/Alexa.NET.APL/4.1.2)

The dimension classes for APL Values (`APLAbsoluteDimensionValue` and `APLDimensionValue`) work correctly and `APLValue.To` now throws an InvalidOperationException if it's tried to be used with any Dimension related class and the error message points you to the dimension classes.

So for your example, the correct assignment would be
`Top = new APLAbsoluteDimensionValue("${Top}")`
or just
`Top = "${Top}"`

Hope this helps, and thanks again for spotting it!
