### ISSUE TITLE
JSON as APLDocument

### ISSUE THREAD

**Issue by evgeni-nabokov** [stoiveyp/Alexa.NET.APL#60]
Hi! I found that it is not convenient to define document layout, resources etc. in C# code. I use the online designing tool https://developer.amazon.com/alexa/console/ask/displays/ that produces JSON document as a result. How can I use that JSON in RenderDocumentDirective as an APLDocument?

**Comment by stoiveyp** [comment]
Hi @evgeni-nabokov - you can store that JSON wherever is easiest for you and then use JSON.Net to produce the document.

I use it to run a lot of my tests, so example code is available here:
https://github.com/stoiveyp/Alexa.NET.APL/blob/master/Alexa.NET.APL.Tests/Utility.cs#L26

**Comment by evgeni-nabokov** [comment]
@stoiveyp I do not like an extra deserialization/serialization round, because it is a redundant operation. Ok, I can live with it for a while, but I am having trouble with deserialization of layout with a container with data field containing data binding expression. The field is simply discarded. How to solve the problem?

**Comment by stoiveyp** [comment]
@evgeni-nabokov it's difficult for me to help you without the code you're having trouble with - do you have an example you could show me?

**Comment by evgeni-nabokov** [comment]
It is not full my code, but very essence. Likely will remove it from here later.
C#
```
            var document = new APLDocument
            {
                MainTemplate = JsonHelper.DeserializeFileContent<Layout>(Path.Combine("UI", screen.ToString(), "MainLayout.json")).AsMain(),
                Layouts = JsonHelper.DeserializeFileContent<Dictionary<string, Layout>>(Path.Combine("UI", screen.ToString(), "Layouts.json")),
                Resources = JsonHelper.DeserializeFileContent<List<Resource>>(Path.Combine("UI", "Common", "Resources.json")),
                Styles = JsonHelper.DeserializeFileContent<Dictionary<string, Style>>(Path.Combine("UI", "Common", "Styles.json")),
            };
            document.AddResponsiveDesign();
            document.Version = APLDocumentVersion.V1_2;
```

MainLayout.json
```
{
  "items": [
    {
      "type": "Container",
      "items": [
       // ...
        {
          "type": "Container",
          "direction": "row",
          "paddingLeft": 20,
          "paddingRight": 20,
          "height": "66vh",
          "width": "100%",
          "items": [
            {
              "type": "IssueListItem",
              "thumbnail": "${data.thumbnail}",
              "title": "{data.title}",
              "date": "{data.date}"
            }
          ],
          "data": "${payload.data.issues}" // <---------- Is not deserialized because Container has the data property of the Dictionary type. 
        }
      ],
      "height": "100vh",
      "width": "100vw"
    }
  ]
}
```

**Comment by evgeni-nabokov** [comment]
I do not see the benefits of making layout in C# as Alexa.NET.APL offers. We have online authoring tool that produces JSON layout. Why do we need do extra job converting JSON into C# every time when we change layouts?

**Comment by stoiveyp** [comment]
@evgeni-nabokov thank you for pointing out the problem with the container object. I'll raise a seperate issue specifically for that when I'm at a computer.

Can I ask why you're using the library for your response you have such strong views against what it does? This feels like you might be better off with the enhanced request object and a custom directive that can send raw JSON? Would that be of more use to you if it were available?

**Comment by evgeni-nabokov** [comment]
I am learning Alexa and APL. I have chosen Alexa.NET.APL because I have already used Alexa.NET. Despite some imperfection, I find the library useful. For example, I like the way of building DataSources for the document. As of custom directive, I think it is a good idea. Using that directive I can combine JSON layout and typed DataSources. I may develop it further.

**Comment by stoiveyp** [comment]
@evgeni-nabokov I've created https://github.com/timheuer/alexa-skills-dotnet/pull/183 to support this request

**Comment by stoiveyp** [comment]
@evgeni-nabokov The latest update to Alexa.NET.APL fixes the issue with container data not being data bound, so your example should now work: https://www.nuget.org/packages/Alexa.NET.APL/4.6.0
