### ISSUE TITLE
Safe Updates to APL Versions with 

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [stoiveyp/Alexa.NET.APL#61]
Hi,

Our code just broke with a call to skillRequest.APLInterfaceDetails()

The device had updated to APL v1.2 and there was an internal Newtonsoft error mapping 1.2 to the APLDocumentVersions.

As skills can be deployed and device updates can happen post deployment, can this section be made safer, avoiding a republish of the skill with a new Alexa.NET.APL package?

**Comment by stoiveyp** [comment]
Hey @Crispin-at-Linknode, definitely something I'll look into as a priority - hopefully updating the package version wasn't too troublesome this time and I'll get something in place before there's a 1.3 :+1:

**Comment by stoiveyp** [comment]
Okay - so as of v4.5.1, if there's a version number it doesn't recognise it goes to `APLDocumentVersion.Unknown` in the version property, and there is a new `MaxVersionString` for raw access.

Same with APLDocumentBase now having `Version` and `VersionString`

https://www.nuget.org/packages/Alexa.NET.APL/4.5.1

Hope this helps
