### ISSUE TITLE
Add opacity to APLcomponent

### ISSUE THREAD

**Issue by nscpt** [stoiveyp/Alexa.NET.APL#68]
Hey man, thank you for doing this project.
Could you add the base component property "opacity" to the APLcomponent class?

[apl documentation](https://developer.amazon.com/de/docs/alexa-presentation-language/apl-component.html#component_opacity_property)

Thank you!

**Comment by stoiveyp** [comment]
Thanks for catching this @nscpt! I can't believe I missed it.

That's been added and is available as of v4.8.0

https://www.nuget.org/packages/Alexa.NET.APL/4.8.0
