### ISSUE TITLE
Filling ListDataSource with Data

### ISSUE THREAD

**Issue by nscpt** [stoiveyp/Alexa.NET.APL#69]
I have a question on how to fill a ListDataSource (which I see has been added fairly recently).
I am currently trying to recreate a Layout I did with the alexa authoring tool in .NET .

So the ListDataSource has different properties like "ListId", while the data is supposed to be stored in the "ListPage", however  the ListPage property is readonly and doesn't have a constructor that takes a parameter.
Can you describe me how it is supposed to be used like? Sorry if this is a trivial question I am no programming pro.

public class ListPage
{
        public ListPage()
             ListItems = new List<object>();

        [JsonProperty("listItems")]
        public List<object> ListItems { get; set; }
}

I guess I could just write my own DataSource type, but I'd rather stick to your classes.

**Comment by stoiveyp** [comment]
Hi @nscpt - thanks for the question. Two ways of filling the data.

1. The list is pre-created, so you can just add the objects you need directly:
`listDataSource.ListPage.ListItems.Add(object1)`

2. The list item has a setter and you can override it with your own list
`listDataSource.ListPage.ListItems = myListOfObjects`

Hope this helps. If I've misunderstood please let me know.
