### ISSUE TITLE
How to build "Karaoke Mode" and survive

### ISSUE THREAD

**Issue by evgeni-nabokov** [stoiveyp/Alexa.NET.APL#71]
I am using the ssmlToSpeech APLTransformer, therefore I do not need (?) to use `ResponseBuilder.Ask` or `ResponseBuilder.Tell`. So, what kind of response I have to build? I am asking because I do not know why my transformation does not work.

```
"datasources": {
	"article": {
		"type": "object",
		"properties": {
			"title": "...",
			"subtitle": "...",
			"ssml": "<speak>I have a dream that one day this nation will rise up and live out the true meaning of its creed: “We hold these truths to be self-evident, that all men are created equal.</speak>"
		},
		"transformers": [
			{
				"inputPath": "ssml",
				"outputName": "speech",
				"transformer": "ssmlToSpeech"
			},
			{
				"inputPath": "ssml",
				"outputName": "text",
				"transformer": "ssmlToText"
			}
		]
	}
}
```

When I use an empty Ask, Alexa simply waits for a command. If I send an empty Tell, Alexa shuts down the skill.

**Comment by stoiveyp** [comment]
Hi @evgeni-nabokov - thanks for the question.

The transformations get the data and speech ready - but you need to tell the display to start speaking. Try sending an ExecuteCommandsDirective along with the RenderDocumentDirective. That should help. 

Here's the command you're after:
https://developer.amazon.com/docs/alexa-presentation-language/apl-standard-commands.html#speakitem-command

Here's my blog article showing how this stuff all fits together (it's APL 1.0 but most of it is relevant)
https://imacode.ninja/2018/11/11/karaoke-mode-with-alexa-net-alexa-presentation-language/

**Comment by evgeni-nabokov** [comment]
@stoiveyp - thank you for reply. I read your good article before. Now I have read it again, found what I missed -- the property Speech of the component Text. I have got reading the speech, but not highlighting of the current sentence. 
You blog does not allow commenting, so I am writing two remarks here.
First, the property `HighlightMode` is not string now, it is the `enum HighlightMode` .
Second, it would be great to post in the article the full final version of the example. My final version, as I mentioned above, does not work in full power (reading + highlighting = karaoke). Could help me with that?

`
var sentences = "Smooth as an android's bottom, eh, Data? About four years." +
    "I got tired of hearing how young I looked. " +
    "Captain, why are we out here chasing comets? " +
    "Fate protects fools, little children and ships named Enterprise.";
var speech = new Speech(new PlainText(sentences));

var mainLayout = new Layout(
               new Container(
                   new ScrollView(
                       new Text()
                       {
                           FontSize = "60dp",
                           TextAlign = "Center",
                           Id = "talker",
                           Content = APLValue.To<string>("${payload.script.properties.text}"),
                           Speech = APLValue.To<string>("${payload.script.properties.speech}")
                       }
                    )
                   { Width = "50vw", Height = "100vw" }
               )
           );
mainLayout.Parameters = new List<Parameter>();
mainLayout.Parameters.Add(new Parameter("payload"));

var directive = new RenderDocumentDirective
{
    Token = "randomToken",
    Document = new APLDocument
    {
        MainTemplate = mainLayout
    },
    DataSources = new Dictionary<string, APLDataSource>
    {
        {
            "script",new ObjectDataSource
            {
                Properties = new Dictionary<string, object>
                {
                    { "ssml", speech.ToXml()}
                },
                Transformers = new List<APLTransformer>{
                    APLTransformer.SsmlToText(
                        "ssml",
                        "text"),
                    APLTransformer.SsmlToSpeech(
                        "ssml",
                        "speech")
                }
            }
        }
    }
};

var response = ResponseBuilder.Empty();
response.Response.Directives.Add(directive);

var speakItem = new SpeakItem
{
    ComponentId = "talker",
    HighlightMode = HighlightMode.Line
};
response.Response.Directives.Add(new ExecuteCommandsDirective("randomToken", speakItem));

return response;
`

**Comment by evgeni-nabokov** [comment]
@stoiveyp Do you have the example working?

**Comment by evgeni-nabokov** [comment]
I found out that highlighting needs a style like this:
```
{
  "styles": {
    "karaokeText": {
      "values": [
        {
          "color": "#fafafa",
          "fontWeight": 300
        },
        {
          "when": "${state.karaoke}",
          "color": "blue",
          "fontWeight": 700
        },
        {
          "when": "${state.karaokeTarget}",
          "color": "white",
          "fontWeight": 100
        }
      ]
    }
  }
}
```

**Comment by evgeni-nabokov** [comment]
Ok, there are states called karaoke and karaokeTarget. There is [information about it](https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-style-definition-and-evaluation.html#karaoke_style_calculations). @stoiveyp your article is good, but it needs to be updated according of the current state of things.
