### ISSUE TITLE
Question: How to add APL support in Azure Functions?

### ISSUE THREAD

**Issue by aalmada** [stoiveyp/Alexa.NET.APL#74]
I have a small voice-only skill and would like to upgrade to use APL.

The current function signature is:

``` csharp
[FunctionName("MyFunction")]
public static IActionResult Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)]SkillRequest req, ILogger log)
{
    log.LogInformation("C# HTTP trigger function processed a request.");

    return req.Request switch
    {
        LaunchRequest _ => new OkObjectResult(ResponseBuilder.Ask("How can I help?", new Reprompt())),

        _ => new OkObjectResult(ResponseBuilder.Empty())
    };
}
```

Do I only need to change the first parameter type to `APLSkillRequest`? I tried but didn't work.

To my best understanding, both the code snippets in the [README](https://github.com/stoiveyp/Alexa.NET.APL/blob/master/README.md) and the [sample](https://github.com/stoiveyp/Alexa.NET.Samples/blob/master/APLTransition/Function.cs) use AWS.

**Comment by aalmada** [comment]
I'm getting the following error in the Azure Portal when setting the first parameter to type `APLSkillRequest`.

```
Error: Microsoft.Azure.WebJobs.Host: Error indexing method 'MyFunction'. Microsoft.Azure.WebJobs.Host: Multiple properties named 'Context' found in type 'APLSkillRequest'.
```

**Comment by stoiveyp** [comment]
Hi @aalmada thanks for reaching out.

We've had this with the core library as well - the underlying issue seems to be that azure functions don't use Json.Net functionality to deserialize the objects, This causes us trouble as we rely on that to work. It isn't an issue for AWS Lambda as they do use Json.Net

If you put the req function signature back to  `HttpRequest req` then you can do something like the following, which should work
```
string requestBody = new StreamReader(await req.Content.ReadAsStreamAsync()).ReadToEnd();
APLSkillRequest skillRequest = JsonConvert.DeserializeObject<APLSkillRequest>(requestBody);
```

Let me know if this helps

**Comment by aalmada** [comment]
Hi @stoiveyp. Thank you so much for the answer.

Almost at the same time I found a very similar solution. Here it is for future reference:

```
[FunctionName("MyFunction")]
public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)]HttpRequest request, ILogger log)
{
    log.LogInformation("Received a request.");

    var payload = await request.ReadAsStringAsync();
    var skillRequest = JsonConvert.DeserializeObject<APLSkillRequest>(payload);

    return skillRequest.Request switch
    {
        LaunchRequest _ 
            => await HandleLaunchRequest(log),

        IntentRequest intent 
            => await HandleIntent(skillRequest, intent, log),

        _ => new OkObjectResult(ResponseBuilder.Empty())
    };
}
```

I'm now going to start really using APL. I'll let you know how it goes.
