### ISSUE TITLE
Component should implement IEnumerable<IComponent>

### ISSUE THREAD

**Issue by aalmada** [stoiveyp/Alexa.NET.APL#75]
The code example for ["Sending a RenderDocument Directive"](https://github.com/stoiveyp/Alexa.NET.APL#sending-a-renderdocument-directive) does not compile because `Component` does not have a constructor that takes an enumerable.

A better implementation is to make `Component` implement `IEnumerable<IComponent>`. This allows the following:

``` csharp
new Container
{
    new Text("APL in C#")
    {
        FontSize = "24dp",
        TextAlign = "Center",
    },
    new Image("https://images.example.com/photos/2143/lights-party-dancing-music.jpg?cs=srgb&dl=cheerful-club-concert-2143.jpg&fm=jpg")
    {
        Width = 400,
        Height = 400,
    },
}
```

The compiler will "automagically" call `Add()` for each `IComponent`. Please check the working [example on sharplab.io](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcAMACOSB0AwgPYA2pApgMbACWxUAzgNzpa5IAsra6bCAZmzoA3umwTcCBMLSTsYufMkA3AIZhsVBsDW0oFTQF5sBgO7YSUXfsPjlExQ4fnLxALYAHBhWsAKAEoAGntnSVcSLx9/YNCw0woLSO8DGJCleISkjxTfYED0zIkInOj82IzlAF8eeSr0et4MIUQ3az0DTRAOAQAeZLKAPlE4sAo1ABMGUgBPbAAZWkZgftLU4EGtNbzGbBNXReXVqPXBwNrJOLgWzmwAQQmJvwH1rZO8gLj5I03td+tGPgHk8/rlrAELg4rkIAJIAUSgEHchjUwGIYGOYI22AA4hRgAikSi0WBArIwj83ljAXiCYjkWBUejzl9LpV4fTieievhaYSGUzSQFyc5KaCyjT8fyuULmGzGmwWjIXnkRmgqkA===).

It will also make possible to enumerate the components in the container.

**Comment by stoiveyp** [comment]
Hi @aalmada 

The link you're referencing does compile - but your example isn't using that code. The example in the documentation uses a constructor - so your example needs to look like this:
```
 var container = new Container
            (
                new Text("APL in C#")
                {
                    FontSize = "24dp",
                    TextAlign = "Center",
                },
                new Image(
                    "https://images.example.com/photos/2143/lights-party-dancing-music.jpg?cs=srgb&dl=cheerful-club-concert-2143.jpg&fm=jpg")
                {
                    Width = 400,
                    Height = 400,
                }
            );
```

The container has to be an APLValue object otherwise there would be deserializing issues when the APL form used data binding instead of object creation.

Hope this helps.

**Comment by aalmada** [comment]
Sorry, I just now realized my code is pointing to `System.ComponentModel.Container`...
