### ISSUE TITLE
Setting slot values from UserEventRequest

### ISSUE THREAD

**Issue by jashton-vintel** [stoiveyp/Alexa.NET.APL#85]
Hey!

I'm trying to elicit slots manually from the user so that I can also present them with APL documents for each turn to allow them to type the information instead of speak it if they wish. I send an ElicitSlot request and display the APL document which works fine. When the user types a value and presses the button I'm using SendEvent which returns me a UserEvent request which contains the information which they have typed. However I'm a little unsure of how to set the slot value to that of the value the user has entered since I don't have a handle on the Slots dictionary in the UserEvent request.. I guess i could use the session attributes and save it for the next turn until i have all the info but this didn't quite feel right. 

I guess i either need to let the ElicitSlot request that the value is coming from either speech or the text input or handle the UserEvent and populate the slot value manually but I'm not too sure how to do either of these.. any ideas?

Not sure if this is a Alexa.NET.APL or Alexa.NET question so sorry if it's not directed at the right place.

**Comment by stoiveyp** [comment]
Hi @jashton-vintel

As the UserEventRequest doesn't have slots, you'll have to handle this yourself. When you respond to the UserEventRequest - respond using ElicitSlot but provide the optional `intent` parameter.

This intent object sets the state of the intent you expect the conversation to carry on with - so you can set the intent name and any slot values you need and it'll carry on as expected from there.

Hope this helps 👍

**Comment by jashton-vintel** [comment]
Works a treat, thank you!!
