### ISSUE TITLE
Alexa headline footer does not work

### ISSUE THREAD

**Issue by TroydonAnabolic** [stoiveyp/Alexa.NET.APL#97]
Footer does not work, in ResponsiveTemplate.cs, possibly the below property needs have it's jsonproperty set to "footerHintText", and also change the property name to FooterHintText ideally too:         

[JsonProperty("hintText", NullValueHandling = NullValueHandling.Ignore)]
public APLValue<string> HintText { get; set; }

to

[JsonProperty("footerHintText", NullValueHandling = NullValueHandling.Ignore)]
public APLValue<string> FooterHintText { get; set; }

**Comment by stoiveyp** [comment]
Thank you for your contribution! Your PR was published in v7.6.1 👍

**Comment by TroydonAnabolic** [comment]
> Thank you for your contribution! Your PR was published in v7.6.1 👍

thanks, my pleasure.
